---
- name: setup firewall via ferm
  hosts: localhost
  tags:
    - firewall
  roles:
    - role: ferm
      tags:
        - ferm
      ferm_input_list:
        - type: "dport_accept"
          filename: "kde_connect_accept"
          dport: ['1714:1764']
          saddr:
            - "192.168.0.0/16"
            - "10.88.0.0/16"
          protocol: "(tcp udp)"
        - type: "dport_accept"
          filename: "local_dev_accept"
          dport: [80,3000]
          saddr:
            - "192.168.0.0/16"
            - "10.88.0.0/16"
        - type: "dport_accept"
          dport: [mdns]
          filename: "mdns_accept"
