---
- name: Provision maschine
  hosts: localhost
  become: true
  roles:
    - role: system
      tags:
        - system
        - setup
      system_user:
        name: "{{ user_name }}"
        id: 1000
      system_zsh_config_path: "{{ zsh_config_path }}"

    - role: fnm
      tags:
        - node
        - fnm
        - nvm
      fnm_user_name: "{{ user_name }}"
      fnm_zsh_config_path: "{{ zsh_config_path }}"

    - role: plasma
      tags:
        - window-manager

    - role: ssd
      tags:
        - ssd

  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"

- import_playbook: firewall.yml

- import_playbook: backup.yml
  when: backup_enabled
