---
- name: provision maschine
  hosts: localhost
  roles:
    - { role: common, tags: [ 'setup' ] }
    - { role: nvm, tags: [ 'node', 'nvm' ] }
    - { role: plasma, tags: [ 'window-manager' ] }
    - { role: ssd, tags: [ 'ssd' ] }
  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"
