---
- name: ensure ferm is installed
  pacman:
    name: "{{ ferm_package }}"
    state: "{{ ferm_package_state }}"
  notify:
    - restart ferm
  become: yes

- name: ensure conntrack is installed
  package:
    name: conntrack-tools
    state: present
  become: yes

- name: ensure configuration directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /etc/ferm/ferm.d
    - /etc/ferm/filter-input.d
  become: yes

- name: ensure firewall is configured
  template:
    src: "{{ item }}.j2"
    dest: /{{ item }}
  with_items:
    - etc/default/ferm
    - etc/ferm/ferm.conf
  notify:
    - restart ferm
  become: yes

- name: ensure iptables INPUT rules are removed
  file: state=absent
        {% if item.filename is defined and item.filename %}
        path=/etc/ferm/filter-input.d/{{ item.weight | default('50') }}_{{ item.filename }}.conf
        {% else %}
        path=/etc/ferm/filter-input.d/{{ item.weight | default('50') }}_{{ item.type }}_{{ item.dport[0] }}.conf
        {% endif %}
  with_flattened:
    - "{{ ferm_input_list }}"
    - "{{ ferm_input_group_list }}"
    - "{{ ferm_input_host_list }}"
  when: ((item.type is defined and item.type) and (item.dport is defined and item.dport)) and
        (item.delete is defined and item.delete)
  become: yes

- name: ensure iptables INPUT rules are added
  template: src=etc/ferm/filter-input.d/{{ item.type }}.conf.j2
            {% if item.filename is defined and item.filename %}
            dest=/etc/ferm/filter-input.d/{{ item.weight | default('50') }}_{{ item.filename }}.conf
            {% else %}
            dest=/etc/ferm/filter-input.d/{{ item.weight | default('50') }}_{{ item.type }}_{{ item.dport[0] }}.conf
            {% endif %}
  with_flattened:
    - "{{ ferm_input_list }}"
    - "{{ ferm_input_group_list }}"
    - "{{ ferm_input_host_list }}"
  when: (item.type is defined and item.type and item.dport is defined and item.dport) and
        (item.delete is undefined or (item.delete is defined and not item.delete))
  become: yes

- name: ensure iptables rules are enabled
  command: ferm --slow /etc/ferm.conf
  changed_when: false
  when: ferm_enabled
  become: yes

- name: ensure iptables rules are disabled
  command: ferm --flush /etc/ferm.conf
  changed_when: false
  when: not ferm_enabled
  become: yes

# force restart of ferm
- name: force restart of ferm
  meta: flush_handlers
