---
# install packages
- name: install packages
  community.general.pacman:
    name: "{{ plasma_packages }}"
    update_cache: yes
    state: present

- name: install kde applications
  community.general.pacman:
    name: "{{ kde_applications }}"
    update_cache: yes
    state: present

- name: Install AUR addon packages
  kewlfft.aur.aur:
    name: "{{ plasma_aur_packages }}"
  become: yes
  become_user: aur_builder
