---
# install packages
- name: install packages
  community.general.pacman:
    name: "{{ plasma_packages }}"
    update_cache: yes
    state: present

- name: install kde applications
  community.general.pacman:
    name: "{{ kde_applications }}"
    update_cache: yes
    state: present

- name: Install AUR addon packages
  aur:
    name: "{{ plasma_aur.packages }}"
    ansible.builtin.user: "{{ user.name }}"
    dir: "/home/{{ user.name }}/{{ plasma_aur.dir }}"
