---
# install packages
- name: install packages
  pacman:
    name: "{{ plasma_packages }}"
    update_cache: yes
    state: present
  notify:
    - enable sddm

- name: install kde applications
  pacman:
    name: "{{ kde_applications }}"
    update_cache: yes
    state: present

- name: Install AUR addon packages
  aur:
    name: "{{ plasma_aur.packages }}"
    user: "{{ user.name }}"
    dir: "/home/{{ user.name }}/{{ plasma_aur.dir }}"
