---
# install packages
- name: install packages
  community.general.pacman:
    name: "sddm"
    update_cache: yes
    state: present
  notify:
    - enable sddm

# set german keymap
- name: set german keymap for sddm
  ansible.builtin.command: localectl set-x11-keymap de
