---
# install packages
- name: install packages
  pacman:
    name: "sddm"
    update_cache: yes
    state: present
  notify:
    - enable sddm

# set german keymap
- name: set german keymap for sddm
  command: localectl set-x11-keymap de
