---
- name: install restic
  community.general.pacman:
    name: restic
    update_cache: True
    state: present

- name: add backup binary
  ansible.builtin.template:
    src: ".local/bin/backup.j2"
    dest: "/home/{{ backup_user_name }}/.local/bin/backup"
    owner: "{{ backup_user_name }}"
    group: "{{ backup_user_name }}"
    mode: 0750

- name: ensure restic config directory exists
  ansible.builtin.file:
    path: "/home/{{ backup_user_name }}/.config/restic"
    state: directory
    mode: 0750
  become: True
  become_user: "{{ backup_user_name }}"

- name: add backup configs
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/home/{{ backup_user_name }}/{{ item }}"
    owner: "{{ backup_user_name }}"
    group: "{{ backup_user_name }}"
    mode: 0640
  with_items:
    - .config/restic/backup.files
    - .config/restic/exclude.files
