---
# install packages
- name: install base packages
  community.general.pacman:
    name: "{{ system_base_packages }}"
    update_cache: yes
    state: present

- name: install development packages
  community.general.pacman:
    name: "{{ system_development_packages }}"
    update_cache: yes
    state: present

# install applications
- name: install applications
  community.general.pacman:
    name: "{{ system_applications }}"
    state: present

- name: install pacman-contrib
  community.general.pacman:
    name: pacman-contrib
    state: present

- name: Enable and start pacman cache cleanup timer
  ansible.builtin.service:
    name: paccache.timer
    state: started
    enabled: yes

- name: Enable color output in pacman
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^#?Color'
    line: "Color"

# AUR
- name: Create AUR directory
  ansible.builtin.file:
    path: "/home/{{ system_user.name }}/{{ system_aur.dir }}"
    state: directory
    owner: "{{ system_user.name }}"
    group: "{{ system_user.name }}"
  tags:
    - aur

- name: Install AUR base packages
  aur:
    name: "{{ system_aur.packages }}"
    user: "{{ system_user.name }}"
    dir: "/home/{{ system_user.name }}/{{ system_aur.dir }}"
  tags:
    - aur
