---
# enable multilib for 32bit apps
- name: Enable multilib repository
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist

# install packages
- name: install base packages
  community.general.pacman:
    name: "{{ system_base_packages }}"
    update_cache: yes
    state: present

- name: install development packages
  community.general.pacman:
    name: "{{ system_development_packages }}"
    update_cache: yes
    state: present

- name: install amd drivers
  community.general.pacman:
    name: "{{ system_amd_packages }}"
    update_cache: yes
    state: present
  when: system_platform == "amd"

- name: install intel drivers
  community.general.pacman:
    name: "{{ system_amd_packages }}"
    update_cache: yes
    state: present
  when: system_platform == "intel"

# install applications
- name: install applications
  community.general.pacman:
    name: "{{ system_applications }}"
    state: present

- name: install pacman-contrib
  community.general.pacman:
    name: pacman-contrib
    state: present

- name: Enable and start pacman cache cleanup timer
  ansible.builtin.service:
    name: paccache.timer
    state: started
    enabled: yes

- name: Enable color output in pacman
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^#?Color'
    line: "Color"

# Mirrorlist updates via reflector
- name: copy reflector config file
  ansible.builtin.template:
    src: "reflector/reflector.conf.j2"
    dest: "/etc/xdg/reflector/reflector.conf"

- name: Enable reflector service for mirrorlist updates on boot
  ansible.builtin.service:
    name: reflector.service
    state: started
    enabled: yes

# AUR
- name: Create AUR directory
  ansible.builtin.file:
    path: "/home/{{ system_user.name }}/{{ system_aur.dir }}"
    state: directory
    owner: "{{ system_user.name }}"
    group: "{{ system_user.name }}"
  tags:
    - aur

- name: Install AUR base packages
  aur:
    name: "{{ system_aur.packages }}"
    user: "{{ system_user.name }}"
    dir: "/home/{{ system_user.name }}/{{ system_aur.dir }}"
  tags:
    - aur
