---
# install packages
- name: install packages
  pacman:
    name: "{{ base_packages }}"
    update_cache: yes
    state: present

# install applications
- name: install applications
  pacman:
    name: "{{ applications }}"
    update_cache: yes
    state: present

- name: install pacman-contrib
  pacman:
    name: pacman-contrib
    update_cache: yes
    state: present

- name: Enable and start pacman cache cleanup timer
  service:
    name: paccache.timer
    state: started
    enabled: yes

# AUR
- name: Create AUR directory
  file:
    path: "/home/{{ user.name }}/{{ aur.dir }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  tags:
    - aur

- name: Install AUR base packages
  aur:
    name: "{{ aur.packages }}"
    user: "{{ user.name }}"
    dir: "/home/{{ user.name }}/{{ aur.dir }}"
  tags:
    - aur
