---

- name: ensure user service directory exist
  file:
    path: "/home/{{ user.name }}/.config/systemd/user"
    state: directory
    mode: 0755
  become: yes
  become_user: "{{ user.name }}"

- name: add user service for ssh-agent
  copy:
    src: "{{ item }}"
    dest: "/home/{{ user.name }}/{{ item }}"
  with_items:
    - .config/systemd/user/ssh-agent.service
  become: yes
  become_user: "{{ user.name }}"

- name: enable ssh-agent service
  systemd:
    name: ssh-agent
    state: started
    enabled: yes
    scope: user
  become: yes
  become_user: "{{ user.name }}"

- name: export ssh auth socket env
  copy:
    src: etc/profile.d/ssh-agent.sh
    dest: /etc/profile.d/ssh-agent.sh
    mode: '0644'
