---
# add admin groups
- name: add admin groups
  group:
    name: "{{ user.name }}"
    gid: "{{ user.id }}"

- name: add sudo group
  group:
    name: sudo

# add admin users
- name: change root user
  user:
    name: root
    shell: /bin/zsh

- name: add admin users
  user:
    name: "{{ user.name }}"
    group: "{{ user.name }}"
    groups:
      - sudo
      - wheel
      - audio
      - video
    shell: /bin/zsh
    password: "{{ user.password }}"

# configure zsh
- name: configure root zsh
  template:
    src: zshrc.j2
    dest: /root/.zshrc.local
    owner: root
    group: root

- name: configure admin zsh
  template:
    src: zshrc.j2
    dest: "/home/{{ user.name }}/.zshrc"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
