---
# add admin groups
- name: add admin groups
  ansible.builtin.group:
    name: "{{ system_user.name }}"
    gid: "{{ system_user.id }}"

- name: add sudo group
  ansible.builtin.group:
    name: sudo

- name: install zsh
  community.general.pacman:
    name:
      - zsh
    update_cache: yes
    state: present

# add admin users
- name: change root user
  ansible.builtin.user:
    name: root
    shell: /bin/zsh

- name: add admin users
  ansible.builtin.user:
    name: "{{ system_user.name }}"
    group: "{{ system_user.name }}"
    groups:
      - sudo
      - wheel
      - audio
      - video
      - uucp
    shell: /bin/zsh
    password: "{{ user_password | password_hash('sha512') }}"
    update_password: on_create

- name: Allow users in sudo group root access
  community.general.sudoers:
    name: allow-sudo-group
    state: present
    group: sudo
    commands: ALL
    nopassword: False

- name: Increase failed login attempts
  ansible.builtin.lineinfile:
    path: /etc/security/faillock.conf
    regexp: '^#?\w+deny'
    line: "deny = 6"

- name: Ensure user bin directory exists
  ansible.builtin.file:
    path: "/home/{{ system_user.name }}/.local/bin"
    state: directory
    mode: 0750
  become: True
  become_user: "{{ system_user.name }}"
