---
# add admin groups
- name: add admin groups
  ansible.builtin.group:
    name: "{{ system_user.name }}"
    gid: "{{ system_user.id }}"

- name: add sudo group
  ansible.builtin.group:
    name: sudo

# add admin users
- name: change root user
  ansible.builtin.user:
    name: root
    shell: /bin/zsh

- name: add admin users
  ansible.builtin.user:
    name: "{{ system_user.name }}"
    group: "{{ system_user.name }}"
    groups:
      - sudo
      - wheel
      - audio
      - video
    shell: /bin/zsh
    password: "{{ user_password | password_hash('sha512') }}"
    update_password: on_create
