---
# add admin groups
- name: add admin groups
  group:
    name: "{{ item.name }}"
    gid: "{{ item.id }}"
  with_items: "{{ admin_users }}"
  become: yes

# add admin users
- name: change root user
  user:
    name: root
    shell: /bin/zsh
  become: yes

- name: add admin users
  user:
    name: "{{ item.name }}"
    group: "{{ item.name }}"
    groups:
      - sudo
    shell: /bin/zsh
    password: "{{ item.password }}"
  with_items: "{{ admin_users }}"
  become: yes

# add grml
- name: add root grml zsh config
  get_url:
    url: https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
    dest: /root/.zshrc
    owner: root
    group: root
  become: yes

- name: add admin grml zsh config
  get_url:
    url: https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
    dest: /home/{{ item.name }}/.zshrc
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: "{{ admin_users }}"
  become: yes

# clone zsh autosuggestions
- name: clone zsh autosuggestions repository
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /usr/share/zsh-autosuggestions
    version: "{{ zsh_autosuggestions_version }}"
  become: yes

# configure zsh 
- name: configure root zsh
  template:
    src: zshrc.local.j2
    dest: /root/.zshrc.local
    owner: root
    group: root
  become: yes

- name: configure admin zsh
  template:
    src: zshrc.local.j2
    dest: "/home/{{ item.name }}/.zshrc.local"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: "{{ admin_users }}"
  become: yes
