---
- name: Install fnm via arch user repository
  kewlfft.aur.aur:
    name: fnm
  become: yes
  become_user: aur_builder

- name: add fnm to zsh config
  ansible.builtin.template:
    src: fnm.zshrc.j2
    dest: "/home/{{ fnm_user_name }}/{{ fnm_zsh_config_path }}/fnm.zshrc"
    owner: "{{ fnm_user_name }}"
    group: "{{ fnm_user_name }}"
