---
- import_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker
  become: yes

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
  become: yes

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers
  when: docker_restart_on_package_change

- import_tasks: docker-compose.yml
  when: docker_install_compose
  become: yes

- import_tasks: install_bindings.yml

- import_tasks: install_packages_tools.yml

# force restart of docker daemon
- name: force restart of docker daemon
  meta: flush_handlers

# get ip of docker0 interface
- name: Register ip of docker0 interface
  shell: ip addr show docker0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1
  register: docker_ip_content
  become: yes
  tags: [ 'redis', 'etherpad', 'ethercalc', 'ldap', 'collabora', 'nextcloud', 'nextcloud.update', 'wordpress', 'mailman', 'mail', 'dovecot', 'mailhog', 'gogs' ]

- set_fact:
    docker_ip: "{{ docker_ip_content.stdout }}"
  tags: [ 'redis', 'etherpad', 'ethercalc', 'ldap', 'collabora', 'nextcloud', 'nextcloud.update', 'wordpress', 'mailman', 'mail', 'dovecot', 'mailhog', 'gogs' ]

# Always restart docker, so docker's iptable rules take precedence over ferm
- name: always restart docker
  service: name=docker state=restarted
  become: yes
