---
- name: Install hdparm
  community.general.pacman:
    name: hdparm
    state: present

- name: Check for TRIM support
  ansible.builtin.shell: "hdparm -I {{ disk_name }} | grep TRIM"
  register: hdparm
  ignore_errors: True

- name: Enable and start weekly filesystem TRIM timer
  ansible.builtin.service:
    name: fstrim.timer
    enabled: yes
    state: started
  when: "hdparm.rc == 0"
